#!/bin/bash

# This script install terraform and its dependencies on linux Ubuntu/Debian
# Author: Azeez Yahaya

# Usage: ./terraform-install

# update ubuntu
sudo apt update

# install gnupg, curl packages and dependencies
sudo apt install -y gnupg software-properties-common

# Install the hashicorp gpg key
wget -O- https://apt.releases.hashicorp.com/gpg | \
gpg --dearmor | \
sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

# Verify the key fingerprint
gpg --no-default-keyring \
--keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
--fingerprint

# Add official hashicorp repo
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
sudo tee /etc/apt/sources.list.d/hashicorp.list

# Download the package info from Hashicorp
sudo apt update

# Install terraform from the new repo
sudo apt-get install terraform -y

# verify the installation
terraform -help

# echo to stdout
sleep 2
echo "############# Congratulations, terraform is installed successfully ###############"; echo ""
echo "Happy hacking!";

